"""initial migration

Revision ID: 0001_initial
Revises: 
Create Date: 2026-02-04 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('nome', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False, unique=True, index=True),
        sa.Column('senha', sa.String(), nullable=False)
    )
    op.create_table('projetos',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('nome', sa.String(), index=True),
        sa.Column('descricao', sa.String()),
        sa.Column('status', sa.String(), nullable=True, server_default='ativo'),
        sa.Column('data_criacao', sa.Text(), nullable=True),
        sa.Column('data_atualizacao', sa.Text(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), sa.ForeignKey('usuarios.id'), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projetos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
